### ISSUE TITLE
assertion fails on 0==0

### ISSUE THREAD

**Issue by CblPOK-git** [NilFoundation/crypto3-multiprecision#38]
Variable_base_scalar_mul test on data {0, 0}, -1 https://github.com/NilFoundation/zkllvm-blueprint/blob/ee0ed71c10775f2a249aecc42db53e55fbdac4d0/test/algebra/curves/plonk/variable_base_scalar_mul.cpp#L166 . Assertion assert(ydata_expected == ydata_real) fails, but should not, because both values are 0

**Comment by martun** [comment]
This was actually fine. The problem was that zero point on a curve is not always (0, 0), for some curves it's (0, 1). And just by chance, if you expected (0,0) but got (0,1), if you compute (0,0) - (0, 1) you will received (0, 1) which is equal to 0. 

This was not the bug, the bug was expecting a (0,0) point if the result is in infinity. That's fixed now.
