### ISSUE TITLE
Remove support of all the backends, except cpp_int

### ISSUE THREAD

**Issue by martun** [NilFoundation/crypto3-multiprecision#64]

**Comment by romanmarkusholler** [comment]
We are using `#include <nil/crypto3/multiprecision/cpp_bin_float.hpp>` which got removed by PRs #63 and #65. As this file was copied from the `boost` library, we tried to use `#include <boost/multiprecision/cpp_bin_float.hpp>` instead which revealed a major problem:

We cannot use `#include <boost/multiprecision/cpp_bin_float.hpp>` together with `crypto3`, as the copied files (from `boost` to `nil/crypto3`) use identical include guards. Could you please change the include guards in `crypto3` so that `boost` becomes usable alongside `crypto3` again?

Problem details:
Using `#include <boost/multiprecision/cpp_bin_float.hpp>` requires to load `#include <boost/multiprecision/cpp_int.hpp>`, but `cpp_int.hpp` from `boost` uses the same include guards as `#include <nil/crypto3/multiprecision/cpp_int.hpp>`, therefore only one of those `cpp_int.hpp` files can get included.

**Comment by martun** [comment]
@romanmarkusholler Sorry for such a late reply, I missed your comment. We are totally redesigning multiprecision, targeting the best performance possible. We will soon change the include guards, and you will not have these problems any more. Meanwhile please use an older version.

Once this PR is merged, the problems must go away: https://github.com/NilFoundation/crypto3-multiprecision/pull/66

**Comment by romanmarkusholler** [comment]
@martun No worries, thank you for your reply! Soon after I created my comment I noticed your activities on some branch (clean_multiprecision_more I think) so I knew that this will get resolved soon.

**Comment by martun** [comment]
@romanmarkusholler It's now resolved.
